services:
  - type: web
    name: medintel-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app/app.py --server.port=$PORT --server.enableCORS=false
    plan: free
